### ISSUE TITLE
The requirement of the public connection to provision R1soft server

### ISSUE THREAD

**Issue by bpersich** [IBM-Bluemix-Docs/software#1]
Comment from  khayama commented on Feb 16 

There must be the caution that the public connection have to be opened to be provisioned with R1soft.
I guess a lot of users have asked to the support with this issue, so you have to update the fact with the following link.

Configure network ports - Server Backup - Server Backup Manager: Wiki | Knowledge Base | Support
http://wiki.r1soft.com/display/ServerBackup/Configure+network+ports

**Comment by bpersich** [comment]
@khayama. I don't understand what is needed here. A public connection on their softlayer server? I looked at your link to the r1soft documentation. Is this the information you are referring to:

_Online activation requires the computer with Backup Manager installed to connect directly to https://activation.r1soft.com:443. Read more in Activate Server Backup Manager._

**Comment by khayama** [comment]
A public connection on their softlayer server?--> Yes.

In detail, the info you referred is correct.
In many cases, the provisioning will be stopped due to the firewall and security groups preventing to connect activation server.
The customer from on-premiss usually do not think this kind of requirements and they would like to close their environment in their private zone including their backup manager server.

So, I would like you to mention this point as a tips or caution in your documentation.

**Comment by bpersich** [comment]
I have added a topic to indicate the firewall requirements:
https://console.bluemix.net/docs/infrastructure/software/configR1Soft.html#configuring-your-filewall-for-r1soft

**Comment by khayama** [comment]
Thanks, please close this issue.
